// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/6f72fc18f1a0d7b344e61642d5bd3720fdb1252e/electron/electron.d.ts
declare module 'electron' {
	var electron: string;
	export = electron;
}
